title: Adekunle Adeboye
logo: ADEKUNLE PASSPORT PHOTO.jpg
description: Iâ€™m a data analyst skilled in SQL, Power BI, and Excel, with experience designing ETL pipelines to clean, model, and visualize data for informed decision-making.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
